In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
samples = [[0, 0, 2], [1, 0, 0], [0, 0, 1]]

In [40]:
neigh = NearestNeighbors(n_neighbors=3, radius=0.4,metric='euclidean') #metric='cosine'
neigh.fit(samples)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='euclidean',
         metric_params=None, n_jobs=1, n_neighbors=3, p=2, radius=0.4)

In [41]:
dist, idx=neigh.kneighbors([[0, 0, 1.3],[1, 0, 0.5]], 2)
print("dist",dist)
print("idx",idx)

dist [[0.3        0.7       ]
 [0.5        1.11803399]]
idx [[2 0]
 [1 2]]


In [42]:
def euclidean_distance(x, y):   
    return np.sqrt(np.sum((x - y) ** 2))

In [44]:
for elem in np.array(samples):
    print(euclidean_distance(elem, np.array([0, 0, 1.3])))

0.7
1.6401219466856727
0.30000000000000004


In [26]:
dist=np.exp(-dist)
dist

array([[0.74081822, 0.4965853 ],
       [0.60653066, 0.3269219 ]])

In [28]:
idx.ravel()

array([2, 0, 1, 2], dtype=int64)

In [31]:
np.array([['a','b'],['c','d']]).ravel()

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [24]:
dist=np.ones(dist.shape)
dist

array([[1., 1.],
       [1., 1.]])

In [38]:
a = np.arange(6).reshape(2,3)+10
print(a)
np.argmin(a,axis=1)

[[10 11 12]
 [13 14 15]]


array([0, 0], dtype=int64)

In [ ]:
a = np.arange(6).reshape(2,3) + 10
a


np.argmin(a)

np.argmin(a, axis=0)

np.argmin(a, axis=1)